### ISSUE TITLE
"ImportError: cannot import name 'insecure_hashlib' from 'huggingface_hub.utils'

### ISSUE THREAD

**Issue by orkhanshamilov** [philschmid/llm-sagemaker-sample#26]
I have this versions of librarys :

huggingface_hub version: 0.24.6
transformers version: 4.44.1
datasets version: 2.13.0
sagemaker version: 2.229.0

Do you have any idea what caused the error?

The error:
---------------------------------------------------------------------------
UnexpectedStatusException                 Traceback (most recent call last)
Cell In[22], line 5
      2 data = {'training': training_input_path}
      4 # starting the train job with our uploaded datasets as input
----> 5 huggingface_estimator.fit(data, wait=True)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/workflow/pipeline_context.py:346, in runnable_by_pipeline.<locals>.wrapper(*args, **kwargs)
    342         return context
    344     return _StepArguments(retrieve_caller_name(self_instance), run_func, *args, **kwargs)
--> 346 return run_func(*args, **kwargs)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/estimator.py:1350, in EstimatorBase.fit(self, inputs, wait, logs, job_name, experiment_config)
   1348 self.jobs.append(self.latest_training_job)
   1349 if wait:
-> 1350     self.latest_training_job.wait(logs=logs)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/estimator.py:2720, in _TrainingJob.wait(self, logs)
   2718 # If logs are requested, call logs_for_jobs.
   2719 if logs != "None":
-> 2720     self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
   2721 else:
   2722     self.sagemaker_session.wait_for_job(self.job_name)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/session.py:5859, in Session.logs_for_job(self, job_name, wait, poll, log_type, timeout)
   5838 def logs_for_job(self, job_name, wait=False, poll=10, log_type="All", timeout=None):
   5839     """Display logs for a given training job, optionally tailing them until job is complete.
   5840 
   5841     If the output is a tty or a Jupyter cell, it will be color-coded
   (...)
   5857         exceptions.UnexpectedStatusException: If waiting and the training job fails.
   5858     """
-> 5859     _logs_for_job(self, job_name, wait, poll, log_type, timeout)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/session.py:8461, in _logs_for_job(sagemaker_session, job_name, wait, poll, log_type, timeout)
   8458             last_profiler_rule_statuses = profiler_rule_statuses
   8460 if wait:
-> 8461     _check_job_status(job_name, description, "TrainingJobStatus")
   8462     if dot:
   8463         print()

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/session.py:8514, in _check_job_status(job, desc, status_key_name)
   8508 if "CapacityError" in str(reason):
   8509     raise exceptions.CapacityError(
   8510         message=message,
   8511         allowed_statuses=["Completed", "Stopped"],
   8512         actual_status=status,
   8513     )
-> 8514 raise exceptions.UnexpectedStatusException(
   8515     message=message,
   8516     allowed_statuses=["Completed", "Stopped"],
   8517     actual_status=status,
   8518 )

UnexpectedStatusException: Error for Training job huggingface-qlora-jailbreaks-mistralai--2024-08-22-08-29-48-606: Failed. Reason: AlgorithmError: ExecuteUserScriptError:
ExitCode 1
ErrorMessage "ImportError: cannot import name 'insecure_hashlib' from 'huggingface_hub.utils' (/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/__init__.py)
 
 The above exception was the direct cause of the following exception
 Traceback (most recent call last)
 File "/opt/ml/code/run_qlora.py", line 12, in <module>
 from transformers import (
 File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
 File "/opt/conda/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1272, in __getattr__
 module = self._get_module(self._class_to_module[name])
 File "/opt/conda/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1284, in _get_module
 raise RuntimeError(
 RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback)
 cannot import name 'insecure_hashlib' from 'huggingface_hub.utils' (/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/

**Comment by orkhanshamilov** [comment]
I solved the issues just by updating all library to latest versions, but now i have probelm about the model:

i have checked and i have valid token but somehow it doesnt work, any ideas?




UnexpectedStatusException: Error for Training job huggingface-qlora-jailbreaks-mistralai--2024-08-22-14-56-40-620: Failed. Reason: AlgorithmError: ExecuteUserScriptError:
ExitCode 1
ErrorMessage "raise EnvironmentError(
 OSError: mistralai/Mistral-7B-v0.1 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
 If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`."
Command "/opt/conda/bin/python3.10 run_qlora.py --bf16 True --dataset_path /opt/ml/input/data/training --gradient_accumulation_steps 2 --gradient_checkpointing True --learning_rate 0.0002 --logging_steps 10 --lr_scheduler_type constant --max_grad_norm 0.3 --merge_adapters True --model_id mistralai/Mistral-7B-v0.1 --num_train_epochs 1 --output_dir /tmp/run --per_device_train_batch_size 6 --save_strategy epoch --tf32 True --use_flash_attn True --warmup_ratio 0.03", exit code: 1
